# Load config:
# const config = require('config')
# Then:
# config.morgan.format

[server]
port = 80
gzip = false

[bunyan]
useStderr = true
level = "warn"

[morgan]
format = "combined"

[session]
secret = "keyboard cat"
